"""Build a portable review page and a text record from local analysis outputs."""
from pathlib import Path
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'site'
manifest = json.loads((OUT / 'evidence/manifest.json').read_text())
findings = json.loads((ROOT / 'analysis/findings.json').read_text())
comparison = json.loads((OUT / 'evidence/glyph-comparison.json').read_text())
word_location = json.loads((OUT / 'evidence/word-location-analysis.json').read_text())
interpretation = json.loads((ROOT / 'analysis/interpretation.json').read_text())
payload = json.dumps({'manifest': manifest, 'findings': findings, 'comparison': comparison, 'wordLocation': word_location, 'interpretation': interpretation}, ensure_ascii=False).replace('</', '<\\/')

template = (ROOT / 'analysis/templates/index.html').read_text()
page = template.replace('__SEGMENTATION_SECTION__', (ROOT/'analysis/segmentation_section.html').read_text())
page = page.replace('__INTERPRETATION_SECTION__', (ROOT/'analysis/interpretation_section.html').read_text())
page = page.replace('__METHOD_SECTION__', (ROOT/'analysis/method_section.html').read_text())
(OUT / 'index.html').write_text(page)
(OUT / 'assets/data.js').write_text('// Generated by analysis/build_review.py. Edit the analysis inputs instead.\nwindow.ANALYSIS_DATA = ' + payload + ';\n')
text_lines = ['Provisional transcription from the supplied screenshot only.',
              '[…] = missing extent, uncounted; ◊ = unreadable surviving trace(s), uncounted; underdot = uncertain letter.',
              'S-numbers identify physical groups, not reconstructed manuscript lines.', '']
for segment in findings['segments']:
    text_lines += [f"{segment['id']}  {segment['text']}", f"  {segment['translation']}", f"  Note: {segment['note']}", '']
(OUT / 'evidence/transcription.txt').write_text('\n'.join(text_lines))
(OUT / 'evidence/interpretation.json').write_text(json.dumps(interpretation, ensure_ascii=False, indent=2) + '\n')
mode_lines = ['PAIRED TRANSCRIPTION AND TRANSLATION MODES', '',
              'These modes distinguish letter reading, contextual completion, reference restoration, and English interpretation.',
              'In modes 2 and 3: {inferred phrase}; [reference-supplied phrase]; […] omitted reference wording.',
              'Tags apply to whole phrases, which can also contain surviving words.',
              'Read mode 1 for exact partial-word boundaries and uncertain letters.', '',
              'MODE 1: IMAGE-ONLY RECORD', ''] + text_lines
for name, full in [('MODE 2: CONTEXTUAL READING', False), ('MODE 3: REFERENCE-LED RECONSTRUCTION', True)]:
    mode_lines += ['', name, '', 'Text order is inferred; physical joins and missing extents are not established.',
                   'The apparent image spellings יומם and לשמים are retained, not silently replaced by the reference.']
    for row in interpretation['rows']:
        mode_lines += ['', f"Genesis 1:{row['verse']}"]
        if row.get('association'):
            mode_lines.append(row['association'])
        for language in ['hebrew', 'english']:
            pieces = []
            for chunk in row['chunks']:
                if not full and not chunk['context']:
                    if not pieces or pieces[-1] != '[…]':
                        pieces.append('[…]')
                    continue
                value = chunk[language]
                if chunk['kind'] == 'inferred': value = '{' + value + '}'
                elif chunk['kind'] == 'supplied': value = '[' + value + ']'
                pieces.append(value)
            mode_lines.append(' '.join(pieces))
mode_lines += ['', 'PHRASE DECISION RECORDS', '']
for row in interpretation['rows']:
    for chunk in row['chunks']:
        mode_lines += [chunk['id'] + ' | ' + chunk['kind'] + ' | ' + (' '.join(chunk['segments']) or 'No surviving segment'),
                       chunk['hebrew'], chunk['english'], chunk['basis'], '']
mode_lines += ['WORKING HYPOTHESES', '']
for hypothesis in interpretation['hypotheses']:
    mode_lines += [hypothesis['title'], hypothesis['preferred'], hypothesis['evidence'],
                   'Alternatives: ' + hypothesis['alternatives'], 'Limit: ' + hypothesis['limit']]
    mode_lines += [source['label'] + ': ' + source['url'] for source in hypothesis['sources']]
    mode_lines.append('')
mode_lines += ['METHOD', ''] + interpretation['method'] + ['', 'SEARCH SCOPE', ''] + interpretation['search_history']
mode_lines += ['', 'Reference: ' + interpretation['reference']['url']]
(OUT / 'evidence/reading-modes.txt').write_text('\n'.join(mode_lines) + '\n')

report = ['# Analysis of the supplied Hebrew fragment screenshot', '',
          'The additional inspection strengthens יומם and לשמים, but it does not securely resolve the isolated upper-right word or complete the bottom-left fragment.',
          'The two damaged groups remain provisional: ב̣ר̣א̣ and ויא̣◊.', '',
          '## Evidence and scope', '',
          f"The sole manuscript-image source was `{manifest['source']}` ({manifest['size'][0]} × {manifest['size'][1]} pixels).",
          f"Its original file SHA-256 is `{manifest['sha256']}`.",
          'The source file was preserved; every crop has recorded pixel coordinates.',
          'The initial image-reading stage used no external edition, external manuscript image, OCR service, or generative restoration.',
          'For the subsequently requested textual-location layer, the Hebrew text of Genesis 1 at Mechon Mamre was opened directly.',
          'The later interpretation stage consulted lexical sources for English meaning and plausible contextual readings.',
          'No reverse image search or manuscript-identification search was performed at any stage.',
          'This was not a blind reading: the previous conversation and familiar wording were already in context.',
          'The within-image comparisons reduce reliance on expected wording, but they cannot eliminate that bias.',
          'No conclusions about date, authenticity, provenance, or manuscript identity are drawn.', '',
          '## Disputed readings', '']
for case in findings['cases']:
    report += [f"### {case['id']}: {case['title']}", '', f"Best visual reading: **{case['reading']}** ({case['status'].lower()}).", '', case['observation'], case['comparison'], case['conclusion'], '', f"Region: `{case['region']}`; source box `{manifest['regions'][case['region']]['box']}`.", '']
report += ['## Image-processing methods', '',
           'The viewer contains unchanged crops and nine derived views per region.',
           'Nearest-neighbor enlargement is used for display, so magnification does not synthesize intermediate pixel values.',
           'The inspection script applies grayscale autocontrast, Gaussian background subtraction, an unsharp mask, thresholds at 65/85/105, and three Wiener inverse filters.',
           'The Wiener filters assume Gaussian blur with sigma 0.65 or 1 source pixel and regularization 0.06 or 0.02.',
           'These blur assumptions were not measured from an original camera image.',
           'The deblurring views did not reveal a decisive stroke absent from the ordinary crops.',
           'Thresholding sometimes merges ink with cracks or the black background, and inverse filtering accentuates noise and creates ringing.',
           'Agreement between processed views is a stability check, not multiple independent observations.',
           'A feature appearing only after processing is not accepted as a recovered letter.', '',
           '## Shape-matching experiment', '',
           'The comparison script uses 17 manually labelled reference crops from the same screenshot and five disputed target crops.',
           'It computes a soft foreground estimate, normalizes crops while preserving aspect ratio, searches translations of -2/0/2 normalized pixels, and compares them by soft Dice overlap.',
           'Specified small rectangles mask portions of damaged edges in two target crops; these masks are recorded in the results.',
           'The experiment sweeps five grayscale levels rather than selecting whichever threshold supports a preferred answer.',
           'A leave-one-out diagnostic at level 85 agreed with 7 of 13 manual labels in classes having at least two examples.',
           'Those labels are provisional human interpretations, not independently verified ground truth.',
           'Some alternative classes have only one reference, and the sample is far too small to estimate general recognition accuracy.',
           'Several target rankings vary with the grayscale level.',
           'Consequently, no numeric overlap score is interpreted as a probability and no reading is accepted because of the matcher.',
           'The full rankings and failures are retained in `glyph-comparison.json`.', '',
           '## Transcription conventions', '',
           'The transcription records physical groups with S-numbers, keeping detached groups separate instead of asserting original line joins.',
           '`[…]` marks a missing extent whose length is not estimated.',
           '`◊` marks surviving but unreadable trace(s), without implying a letter count.',
           'In the image-only record, an underdot marks an uncertain letter, and no bracketed Hebrew completions are supplied.',
           'The English renderings preserve fragmentary syntax where necessary; bracketed English words are grammatical supplementation.',
           'The Hebrew spelling יומם is preserved; its vocalization and precise contextual function are not established from this screenshot.',
           'The final fragment is not expanded to a complete verb.',
           'Faint marks outside the listed groups are not confidently distinguished as letters.', '',
           '## Reproduce the work', '',
           'From the workspace root:', '',
           '```sh',
           'python3 -m venv .venv',
           '.venv/bin/python -m pip install -r analysis/requirements.txt',
           '.venv/bin/python analysis/inspect_manuscript.py',
           '.venv/bin/python analysis/compare_glyphs.py',
           '.venv/bin/python analysis/segment_and_locate.py',
           '.venv/bin/python analysis/build_review.py',
           '```', '',
           'Run `npm run dev` and open the printed local URL for the standalone evidence viewer.',
           'The crop manifest records all coordinates and filter settings.',
           'The viewer loads its generated data file, scripts, styles, and image assets from the same static site.',
           'The source image itself is not uploaded by the viewer.', '',
           '## Verification performed', '',
           'The original file hash was unchanged, and the RGB source copy and all 26 unchanged crops were checked for exact pixel equality.',
           'All 260 region views retained the expected source-crop dimensions, and all 15 transcription records referenced existing regions.',
           'In Chrome, all four case selectors, all ten processing modes on the selected test crop, the original-view toggle, magnification, and frame fitting were exercised successfully.',
           'The page loaded without broken images and had no document-level horizontal overflow at measured widths of 1278 and 390 CSS pixels.',
           'Desktop and emulated mobile screenshots were visually inspected.',
           'The raw matcher audit was checked against the reported 7-of-13 label agreement.', '',
           'For the added segmentation layer, all 64 word-window crops were checked for exact source-pixel equality.',
           'All 15 physical-group selectors, word selection, overlay toggling, and all three spacing thresholds were exercised in Chrome.',
           'The added sections had no document-level overflow at 390 CSS pixels, and both desktop and mobile renderings were visually inspected.',
           'The reference alignment check confirmed the S10 crossing from 1:7 to 1:8 and retained both exact within-range matches for S14.', '',
           '## Remaining evidence limit', '',
           'Additional filters applied to this screenshot do not provide an independent observation of the damaged writing.',
           'A higher-resolution source photograph or an image with different illumination could supply information that is absent here.',
           'The existing analysis supports a better documented provisional reading, not a fully resolved academic edition.', '']
word_report = ['## Added analysis: word segmentation and textual location', '',
               'This layer separates physical graphic-word segmentation, grammatical prefix analysis, and placement in a reference text.',
               'It was added after the original image-based readings, at the user’s request.',
               'The reference was opened directly, without searching for the image or manuscript identity: [Mechon Mamre, Genesis 1, Hebrew text](https://mechon-mamre.org/p/pt/pt0101.htm).', '',
               '### Word segmentation', '',
               'There are 64 manually annotated word or partial-word windows across 15 physical groups.',
               'The windows are approximate source-pixel rectangles, not automatic OCR output or traced ink contours.',
               'They were inspected as an atlas; all crop pixels come directly from the source.',
               'Ordering within each group follows Hebrew reading direction, from right to left.',
               'Missing stretches are not assigned word counts.',
               'Prefixes such as ו and ל remain attached to their written words; grammatical decomposition is shown separately.',
               'For example, ולחשך can be analysed as ו + ל + חשך without asserting any spaces between these components.', '',
               'The day-word spacing was measured in the original grayscale band x=390–601, y=545–591.',
               'At thresholds 65, 85, and 105, a low-ink column means fewer than three pixels below the threshold; runs at least three columns wide are recorded.',
               'The exterior low-ink runs measure 20–23 pixels on the left and 30–32 on the right; interior runs measure only 3–6 pixels.',
               'No internal vertical gap separates the two mem-shaped structures.',
               'This supports one graphic word rather than splitting יומם into two spaced words, but it cannot establish the individual letters by itself.',
               'The occupancy rule is a local diagnostic, not a universal boundary detector.', '',
               '### Textual locations', '',
               '| Physical group | Likely reference location | Basis |',
               '| --- | --- | --- |']
for row in word_location['rows']:
    word_report.append(f"| {row['id']} | {row['location']} | {row['strength']} |")
word_report += ['',
                'The longer phrases align with Genesis 1:1–10; the final prefix could begin 1:11 only as a contextual hypothesis.',
                'The software compares equal-length contiguous token windows within Genesis 1:1–11 using a normalized character-edit cost, with explicit penalties for incomplete or uncertain tokens.',
                'Pointing, cantillation, punctuation, and maqaf are removed for matching; consonantal differences are preserved.',
                'It does not search the whole Bible and does not model insertion or deletion of entire words.',
                'Costs rank matches; they are not probabilities or letter-identification confidence scores.',
                'The complete reference strings, word windows, spacing profiles, and five leading candidates per group are retained in `word-location-analysis.json`.', '',
                'S14, כי טוב, matches both 1:4 and 1:10 within this restricted range; its physical and sequential context favors 1:10.',
                'S06, ויקרא, occurs at 1:5, 1:8, and 1:10; its position beside S05 favors 1:5.',
                'S15 does not independently identify 1:11: the prefix is short, damaged, and compatible with a repeated verb.',
                'S10 crosses the modern verse boundary between 1:7 and 1:8.',
                'Text order suggests associations of S02 before S01 and S06 before S05, but does not prove physical joins.',
                'Genesis 1:3 has no securely transcribed surviving group here; this does not demonstrate a scribal omission.', '',
                '### Apparent differences and limits', '',
                'The provisional image reading יומם differs from reference יום at 1:5.',
                'The provisional image reading לשמים differs from reference השמים at 1:9.',
                'The reference text is not used to silently replace those image readings.',
                'These are apparent differences from one reference edition, not established manuscript variants.',
                'Verse numbering is modern reference metadata and is not visible in the fragment.',
                'Neither phrase alignment nor word-window annotation establishes original column width, missing text length, the fit of restored words in tears, provenance, or authenticity.', '']
insert_at=report.index('## Verification performed')
report[insert_at:insert_at]=word_report
interpretive_report = ['## Paired transcription and translation modes', '',
                      'The user subsequently requested inference and hypothesis, with explicit distinctions for both transcription and translation.',
                      'Mode 1 is the image-only physical-group record: partial words, lacunae, and uncertain letters are preserved, and English stays fragmentary.',
                      'Mode 2 is a contextual edited Hebrew reading and working English translation, arranged in likely textual order.',
                      'It completes damaged words provisionally and includes a few explicitly marked reference supplies for readability, leaving larger losses as lacunae.',
                      'Mode 3 is a fuller reference-led reconstruction of Genesis 1:1–10, with all reference-supplied phrases marked.',
                      'It retains יומם and לשמים as provisional image spellings rather than harmonizing them with the comparison edition.',
                      'These are differences in evidential scope, not three increasing confidence levels.',
                      'In the contextual and reconstruction modes, inferred words receive an inference label instead of underdots.',
                      'That display convention does not upgrade their certainty; the exact surviving portions remain in mode 1.',
                      'Phrase-level labels follow the least directly observed essential wording: an inferred or supplied phrase may also include surviving words.',
                      'An image-based phrase still requires choices of English grammar and meaning.',
                      'English word order need not correspond word for word to the paired Hebrew.', '',
                      '### Decision method', ''] + interpretation['method'] + ['',
                      '### Search and reference scope', ''] + interpretation['search_history'] + ['',
                      '### Interpretive conclusions and alternatives', '']
for hypothesis in interpretation['hypotheses']:
    interpretive_report += ['#### ' + hypothesis['title'], '', hypothesis['preferred'], hypothesis['evidence'],
                           'Alternatives: ' + hypothesis['alternatives'], 'Limit: ' + hypothesis['limit']]
    interpretive_report += ['[' + source['label'] + '](' + source['url'] + ')' for source in hypothesis['sources']]
    interpretive_report.append('')
interpretive_report += ['All paired texts and phrase decision records are downloadable as `reading-modes.txt`.',
                       'Structured provenance, hypotheses, and sources are in `interpretation.json`.',
                       'These are provisional readings and a documented interpretive exercise, not an independently reviewed critical edition.', '']
insert_at=report.index('## Verification performed')
report[insert_at:insert_at]=interpretive_report
verification_at=report.index('## Remaining evidence limit')
report[verification_at:verification_at]=[
    '### Standalone viewer and paired-reading validation', '',
    'The static build packages 334 evidence files and local interface assets without Python or a Lavish runtime.',
    'All 39 interpretive phrase records reference valid segment and hypothesis identifiers.',
    'The ten reconstructed Hebrew verse strings were checked against the declared reference, allowing only the two explicitly retained image spellings יומם and לשמים.',
    'All of verse 3 is marked reference-supplied and omitted in the contextual mode.',
    'The original phrase-dialog interface was checked in Chrome before the reading flow was simplified.',
    'The revised interface has three accessible tabs with a sliding underline for strict, contextual, and reconstructed readings, with no phrase dialogs.',
    'All 39 phrase records remain in the fuller reconstruction notes; the strict mode retains all 15 physical groups and is the default.',
    'The passage-note link to an image crop, the return link to the same passage, direct version URLs, browser Back, tab keyboard navigation, and reduced-motion behavior were exercised in Chromium.',
    'English-choice explanations now appear as plain text, with alternatives in the passage notes.',
    'Inspection and methodology now use four and two tabs respectively, with one visible card per section and matching heading-and-description blocks.',
    'All six new panels, keyboard navigation, history, direct links, and links between readings, crops, and word analysis were checked in Chromium.',
    'Computed tab typography, padding, height, and underline styling match across all three sections at desktop and mobile widths.',
    'A phrase-to-image link selected the correct physical crop, and all eight linked evidence downloads returned successful responses.',
    'Desktop and mobile screenshots of the revised reading page and inline notes were inspected.',
    'The magazine-style opening was checked at 1536×632, 1280×720, 1440×900, 390×844, and 390×667: the image, contents, and usage guide fit in the first viewport, with the reading section below it.',
    'There was no document-level horizontal overflow at 1280 or 390 CSS pixels, no broken loaded images, no external runtime requests, and no browser JavaScript errors.', '',
]
report_text = '\n'.join(re.sub(r'(?<=[.!?]) (?=[A-Z])', '\n', line) for line in report)
(ROOT / 'analysis/REPORT.md').write_text(report_text)
(OUT / 'evidence/analysis-report.md').write_text(report_text)
print(OUT / 'index.html')
